const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const box={module:{exports:{}}};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../web/public/audience/engine.js'),'utf8'),box);const E=box.module.exports;
function ready(){const t=E.create(E.scenarios.travel.query,'travel');for(const [k,f] of Object.entries(t.fields)){f.value=k==='window'?'30':k==='domain'?'生服':'演示已确认';f.status='已确认';}E.confirm(t);E.select(t,['balanced']);t.conditionConfirmed=true;return t;}
test('unconfirmed fields block strategy generation',()=>{const t=E.create('圈出近期想出游的人','travel');assert.throws(()=>E.confirm(t),/必要信息/);assert.throws(()=>E.select(t,['balanced']),/确认需求/);});
test('non-audience tasks cannot flow to execution',()=>{for(const q of ['分析用户有什么特点','建设底表','制定年度规划','开发新的弹窗功能']){const t=E.create(q);assert.notEqual(t.type,'直接圈人');assert.throws(()=>E.confirm(t));}});
test('confirmed stages allow a complete demo, adoption is not evidence',()=>{const t=ready();assert.equal(E.executable(t),true);E.run(t);E.approve(t);assert.equal(t.stage,5);assert.equal(t.result.version,t.version);assert.equal(t.adoption,'未采纳');assert.match(t.result.sql,/不可用于生产/);});
test('every core blocker prevents run',()=>{for(const key of ['missing','permission','definition','mapping','stale','model']){const t=ready();t.blocker=key;assert.equal(E.executable(t),false);assert.throws(()=>E.run(t),/禁止执行/);assert.equal(t.runs.length,0);}});
test('missing condition and lost permissions cannot execute',()=>{const t=ready();t.conditions[0].value='';assert.equal(E.executable(t),false);t.conditions[0].value='x';t.conditions[0].permission='未授权';assert.equal(E.executable(t),false);});
test('upstream edits invalidate current result and preserve snapshot',()=>{const t=ready();E.run(t);E.approve(t);const old=E.clone(t.result);E.revise(t,3,'修改条件');assert.equal(t.result,null);assert.equal(t.version,2);assert.deepEqual(t.versions[0].result,old);assert.equal(t.confirmed,true);assert.equal(t.conditionConfirmed,false);assert.throws(()=>E.approve(t));});
test('editing intent requires renewed strategy confirmation',()=>{const t=ready();E.revise(t,1,'修改需求');assert.equal(t.confirmed,false);assert.equal(t.strategyConfirmed,false);assert.equal(t.conditions.length,0);});
test('three consecutive failed runs stop retry even after revisions',()=>{const t=ready();E.run(t,'sql');E.run(t,'sample');E.run(t,'sql');assert.equal(t.attempts,3);assert.throws(()=>E.run(t),/三轮/);E.revise(t,3,'修改阈值');t.conditionConfirmed=true;assert.throws(()=>E.run(t),/三轮/);});
test('successful run clears failure streak',()=>{const t=ready();E.run(t,'sql');E.run(t);assert.equal(t.attempts,0);});
test('LDMP entry cannot execute cross-domain conditions',()=>{const t=ready();t.scope='ldmp';t.fields.domain.value='跨域';assert.equal(E.executable(t),false);assert.throws(()=>E.confirm(t),/仅限生服/);});
test('restore makes a new version, preserves history and requires reconfirmation',()=>{const t=ready();E.run(t);E.revise(t,3,'edit');E.restore(t,1);assert.equal(t.version,3);assert.equal(t.result,null);assert.equal(t.confirmed,false);assert.equal(t.fields.object.status,'待确认');assert.equal(t.versions.length,2);});

test('seed coverage is absent until a seed reference is supplied',()=>{const t=ready();E.run(t);assert.equal(t.result.seed,null);t.seedRef='DEMO-SEED-01';E.run(t);assert.equal(t.result.seed,92);});

test('empty IR cannot execute',()=>{const t=ready();t.conditions=[];assert.equal(E.executable(t),false);assert.throws(()=>E.run(t));});
