const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const box={module:{exports:{}}};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../web/public/audience/engine.js'),'utf8'),box);const E=box.module.exports;
function ready(){const t=E.create('为品牌找近30天搜索或收藏羽绒服且服饰消费分层L3及以上的用户','brand');E.confirm(t);E.select(t,['balanced']);t.conditionConfirmed=true;return t;}
test('unconfirmed fields block strategy generation',()=>{const t=E.create('圈出近期想出游的人','travel');assert.throws(()=>E.confirm(t),/关键口径/);assert.throws(()=>E.select(t,['balanced']),/确认需求/);});
test('non-audience tasks cannot flow to execution',()=>{for(const q of ['分析用户有什么特点','建设底表','制定年度规划','开发新的弹窗功能']){const t=E.create(q);assert.notEqual(t.type,'直接圈人');assert.throws(()=>E.confirm(t));}});
test('confirmed stages allow a complete demo, adoption is not evidence',()=>{const t=ready();assert.equal(E.executable(t),true);E.run(t);E.approve(t);assert.equal(t.stage,5);assert.equal(t.result.version,t.version);assert.equal(t.adoption,'未采纳');assert.match(t.result.sql,/不可用于生产/);});
test('every core blocker prevents run',()=>{for(const key of ['missing','permission','definition','mapping','stale','model']){const t=ready();t.blocker=key;assert.equal(E.executable(t),false);assert.throws(()=>E.run(t),/禁止执行/);assert.equal(t.runs.length,0);}});
test('missing condition and lost permissions cannot execute',()=>{const t=ready();t.conditions[0].value='';assert.equal(E.executable(t),false);t.conditions[0].value='x';t.conditions[0].permission='未授权';assert.equal(E.executable(t),false);});
test('upstream edits invalidate current result and preserve snapshot',()=>{const t=ready();E.run(t);E.approve(t);const old=E.clone(t.result);E.revise(t,3,'修改条件');assert.equal(t.result,null);assert.equal(t.version,2);assert.deepEqual(t.versions[0].result,old);assert.equal(t.confirmed,true);assert.equal(t.conditionConfirmed,false);assert.throws(()=>E.approve(t));});
test('editing intent requires renewed strategy confirmation',()=>{const t=ready();E.revise(t,1,'修改需求');assert.equal(t.confirmed,false);assert.equal(t.strategyConfirmed,false);assert.equal(t.conditions.length,0);});
test('three consecutive failed runs stop retry even after revisions',()=>{const t=ready();E.run(t,'sql');E.run(t,'sample');E.run(t,'sql');assert.equal(t.attempts,3);assert.throws(()=>E.run(t),/三轮/);E.revise(t,3,'修改阈值');t.conditionConfirmed=true;assert.throws(()=>E.run(t),/三轮/);});
test('successful run clears failure streak',()=>{const t=ready();E.run(t,'sql');E.run(t);assert.equal(t.attempts,0);});
test('LDMP entry cannot execute cross-domain conditions',()=>{const t=ready();t.scope='ldmp';t.fields.domain.value='跨域';assert.equal(E.executable(t),false);assert.throws(()=>E.confirm(t),/仅限生服/);});
test('restore makes a new version, preserves history and requires reconfirmation',()=>{const t=ready();E.run(t);E.revise(t,3,'edit');E.restore(t,1);assert.equal(t.version,3);assert.equal(t.result,null);assert.equal(t.confirmed,false);assert.equal(t.fields.object.status,'原话提取');assert.equal(t.versions.length,2);});

test('seed coverage is absent until a seed reference is supplied',()=>{const t=ready();E.run(t);assert.equal(t.result.seed,null);t.seedRef='DEMO-SEED-01';E.run(t);assert.equal(t.result.seed,92);});

test('empty IR cannot execute',()=>{const t=ready();t.conditions=[];assert.equal(E.executable(t),false);assert.throws(()=>E.run(t));});

test('brand starter asks only interest and spending, no redundant field approvals',()=>{const t=E.create(E.scenarios.brand.query);assert.deepEqual(Array.from(E.missing(t)),['interest','spending']);assert.equal(t.fields.window.value,'90');E.answer(t,'interest','搜索或收藏');E.answer(t,'spending','服饰分层L3及以上');assert.equal(E.missing(t).length,0);E.confirm(t);assert.equal(t.confirmed,true);});
test('fully explicit brief needs no clarification or invented KPI',()=>{const t=ready();assert.equal(E.missing(t).length,0);assert.match(t.fields.platform.value,/补充/);assert.equal(t.fields.window.value,'30');});
test('ordinary coupon audience is not mistaken for uplift',()=>assert.notEqual(E.detect('为品牌找近30天买过鞋的用户发券'),'uplift'));
test('missing lookback cannot silently default to 30 days',()=>{const t=E.create('为品牌找搜索羽绒服的用户');assert.ok(E.missing(t).includes('window'));assert.equal(t.fields.window.value,'');assert.throws(()=>E.answer(t,'window','0'));E.answer(t,'window','60');assert.equal(t.fields.window.value,'60');});
test('new customer scenario requires brand identity and purchase lookback',()=>{const t=E.create(E.scenarios.acquisition.query);assert.deepEqual(Array.from(E.missing(t)),['brandScope','newCustomer']);});
test('distance targeting asks for store reference only when selected',()=>{const t=E.create(E.scenarios.local.query);E.answer(t,'interest','搜索火锅');E.answer(t,'area','门店周边3公里');assert.ok(E.missing(t).includes('store'));assert.throws(()=>E.answer(t,'store','real-id'));E.answer(t,'store','DEMO-STORE-01');assert.equal(E.missing(t).length,0);});
test('decisions survive restoration but downstream approvals do not',()=>{const t=E.create(E.scenarios.brand.query);E.answer(t,'interest','主动搜索');E.answer(t,'spending','服饰L3以上');E.confirm(t);E.select(t,['balanced']);t.conditionConfirmed=true;E.run(t);E.revise(t,1,'重新理解');E.restore(t,1);assert.equal(t.decisions.interest,'主动搜索');assert.equal(t.confirmed,false);assert.equal(t.result,null);});

test('SQL groups alternatives and exclusions while preserving required conditions',()=>{const t=ready();const sql=E.sql(t);assert.match(sql,/WHERE condition_1 = TRUE\n    AND condition_2 = TRUE/);assert.match(sql,/AND \(condition_3 = TRUE\)/);assert.match(sql,/AND NOT \(condition_5 = TRUE OR condition_6 = TRUE\)/);assert.ok(t.conditions.some(c=>c.locked&&c.group==='排除'));});
test('exploration annotates candidates instead of silently relaxing core eligibility',()=>{const t=ready();E.select(t,['explore']);const extra=t.conditions.find(c=>c.group==='辅助分层');assert.ok(extra);assert.equal(extra.core,false);assert.equal(extra.locked,true);const index=t.conditions.indexOf(extra)+1;assert.ok(!E.sql(t).includes('condition_'+index+' = TRUE'));assert.match(t.conditions.find(c=>c.name==='策略信号范围').value,/不额外限制/);});
test('restoring an older interpretation restores the original query and scenario',()=>{const t=ready();const q=t.query;E.revise(t,1,'改成召回');t.query='近90天美妆召回';t.scenario='recall';E.restore(t,1);assert.equal(t.query,q);assert.equal(t.scenario,'brand');assert.equal(t.confirmed,false);assert.equal(t.conditions.length,0);});

test('operation receipts stay waiting and never complete downstream work',()=>{const t=ready();const a=E.beginActivity(t,'理解',[{title:'提取'},{title:'追问'},{title:'生成'}]);E.updateActivity(t,a.id,0,'done','提取完成');E.updateActivity(t,a.id,1,'waiting','缺时间');assert.equal(a.status,'waiting');assert.equal(a.items[2].status,'pending');});
test('revising cancels running operations and ignores stale updates',()=>{const t=ready();const a=E.beginActivity(t,'执行',[{title:'查询'}]);E.updateActivity(t,a.id,0,'running');E.revise(t,1,'修改需求');assert.equal(a.status,'cancelled');assert.equal(E.updateActivity(t,a.id,0,'done','旧结果'),false);});
test('handoff gates and receipt versions prevent stale or duplicate results',()=>{const t=ready();t.conditionConfirmed=false;assert.throws(()=>E.prepareHandoff(t));t.conditionConfirmed=true;const h=E.prepareHandoff(t);const receipt={requestId:h.requestId,taskId:t.id,version:t.version,resultVersion:t.version,status:'completed',sql:E.sql(t)};assert.throws(()=>E.acceptHandoff(t,{...receipt,version:99}),/版本/);E.acceptHandoff(t,receipt);assert.equal(h.status,'completed');assert.throws(()=>E.acceptHandoff(t,receipt),/重复/);});
test('failed handoff preserves conditions and records cause without relaxing them',()=>{const t=ready();const before=JSON.stringify(t.conditions),h=E.prepareHandoff(t);E.acceptHandoff(t,{requestId:h.requestId,taskId:t.id,version:t.version,status:'failed',reason:'SQL 错误'});assert.equal(h.status,'failed');assert.equal(JSON.stringify(t.conditions),before);});

test('mutually exclusive base strategies cannot be combined',()=>{const t=ready();assert.throws(()=>E.select(t,['balanced','conservative']),/只能选择一种/);E.select(t,['conservative','explore']);assert.ok(t.conditions.some(c=>c.value.includes('2次')));assert.ok(t.conditions.some(c=>c.group==='辅助分层'));});
test('evidence requires reviewed current result, full provenance, and keeps its version',()=>{const t=ready();const input={experiment:'DEMO-EXP',metric:'转化率 %',control:'2%',treatment:'2.2%',period:'示例日期与范围',source:'DEMO-LR',conclusion:'样本不足，未验证收益'};assert.throws(()=>E.recordEvidence(t,input),/复核/);E.run(t);E.approve(t);assert.throws(()=>E.recordEvidence(t,{...input,source:''}),/补齐/);const e=E.recordEvidence(t,input);assert.equal(e.version,1);assert.match(e.kind,/未自动核验/);E.revise(t,3,'调整');assert.equal(t.evidence[0].version,1);assert.equal(t.evidence.filter(e=>e.version===t.version).length,0);assert.throws(()=>E.recordEvidence(t,input),/复核/);});
test('template reuse preserves edited business rules while rechecking strategy controls',()=>{const source=ready();source.conditions[0].value='近 90 天服饰订单至少 3 单';const t=E.create(source.query);t.templateConditions=E.clone(source.conditions);E.confirm(t);E.select(t,['conservative','explore']);assert.equal(t.conditions[0].value,'近 90 天服饰订单至少 3 单');assert.equal(t.conditionConfirmed,false);assert.equal(t.result,null);assert.ok(t.conditions.find(c=>c.name==='策略信号范围').value.includes('2次'));assert.equal(source.conditions.find(c=>c.name==='策略信号范围').value.includes('2次'),false);});
